version: '3.3'
services:
  docs:
    image: swaggerapi/swagger-editor
    restart: always
    environment:
      URL: /api
    ports:
      - 80:8080
  db:
    image: mariadb:10.5.8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      TZ: Asia/Manila
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./environment/mysql:/var/lib/mysql
  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"